# Generated by Django 3.2.5 on 2022-09-05 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Not_Active', 'Not_Active')], default='Active', max_length=15)),
                ('Type', models.CharField(max_length=30)),
                ('Size_in_Feet_Squared', models.IntegerField()),
                ('Farm_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Crop_Variety', models.CharField(max_length=20)),
                ('Notes', models.TextField()),
                ('Farm_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Crop_Variety', models.CharField(max_length=30)),
                ('Plant_Date', models.DateTimeField()),
                ('Notes', models.TextField()),
                ('Farm_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=50)),
                ('Size_in_Hectares', models.IntegerField()),
                ('Type', models.CharField(choices=[('Bed', 'Bed'), ('Field', 'Field'), ('Paddock', 'Paddock'), ('Property', 'Property'), ('Other', 'Other')], max_length=20)),
                ('Farm_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Color', models.CharField(max_length=20)),
                ('Manufacturer', models.CharField(max_length=30)),
                ('Serial_No', models.CharField(max_length=20)),
                ('Date_Acquired', models.DateTimeField()),
                ('Notes', models.TextField()),
                ('Farm_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Species', models.CharField(max_length=20)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Not_Active', 'Not_Active')], default='Active', max_length=15)),
                ('Birth_Date', models.DateTimeField(auto_now_add=True)),
                ('Sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('Tag_ID', models.CharField(max_length=10, unique=True)),
                ('Tag_Location', models.CharField(max_length=20)),
                ('Farm_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
