# Generated by Django 3.2.5 on 2022-09-08 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Farm_ID',
        ),
    ]
