# Generated by Django 3.2.5 on 2022-09-05 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planting_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season', models.CharField(max_length=20)),
                ('Crop_Variety', models.CharField(max_length=20)),
                ('Number_of_Varieties', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('Inputs', models.CharField(max_length=20)),
                ('Farm_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Log_Name', models.CharField(max_length=20)),
                ('Asset_Affected', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=20)),
                ('Veterinarian', models.CharField(max_length=30)),
                ('Farm_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asset', models.CharField(max_length=20)),
                ('Date', models.DateTimeField()),
                ('Equipment_Used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.equipment')),
                ('Farm_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Harvest_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Log_Name', models.CharField(max_length=20)),
                ('Date', models.DateTimeField()),
                ('Asset', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=20)),
                ('Quantity', models.CharField(max_length=20)),
                ('Storage_ID', models.CharField(max_length=5)),
                ('Equipment_Used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.equipment')),
                ('Farm_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Farm_Input_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Log_Name', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=20)),
                ('Material_Type', models.CharField(max_length=20)),
                ('Source', models.CharField(max_length=20)),
                ('Quantity', models.CharField(max_length=20)),
                ('Farm_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Birth_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Veterinarian', models.CharField(max_length=30)),
                ('Species', models.CharField(max_length=20)),
                ('Notes', models.TextField()),
                ('Equipment_Used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.equipment')),
                ('Farm_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Mother_by_TagID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.animal')),
            ],
        ),
    ]
