# Generated by Django 3.2.5 on 2022-09-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth_logs',
            name='Equipment_Used',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='harvest_logs',
            name='Equipment_Used',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenance_logs',
            name='Equipment_Used',
            field=models.CharField(max_length=100),
        ),
    ]
